---
# task/configure file for hashicorp_vault
- name: "Ensure default vault.hcl is removed"
  ansible.builtin.file:
    path: /etc/vault.d/vault.hcl
    state: absent

- name: "Copy vault.json template"
  ansible.builtin.template:
    src: vault.json.j2
    dest: "{{ hashi_vault_config_dir }}/vault.json"
    owner: "{{ hashi_vault_user }}"
    group: "{{ hashi_vault_group }}"
    mode: '0600'
  notify:
    - "systemctl-enable-vault"
    - "systemctl-restart-vault"

- name: "Create vault.env"
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ hashi_vault_config_dir }}/vault.env"
    owner: "{{ hashi_vault_user }}"
    group: "{{ hashi_vault_group }}"
    mode: '0600'
