---
# task/install file for hashicorp_vault
- name: "Configure hashicorp repository"
  ansible.builtin.include_role:
    name: ednxzu.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo:
      - uri: "https://apt.releases.hashicorp.com"
        gpg_key: "https://apt.releases.hashicorp.com/gpg"
        comments: "hashicorp repository"
        type: "deb"
        suites: "{{ ansible_distribution_release }}"
        components: "main"
        filename: "hashicorp"

- name: "Install vault:{{ hashi_vault_version }}"
  ansible.builtin.include_role:
    name: ednxzu.manage_apt_packages
  vars:
    manage_apt_packages_list:
      - name: vault
        version: "{{ hashi_vault_version }}"
        state: present

- name: "Copy systemd service file for vault"
  ansible.builtin.template:
    src: "nomad.service.j2"
    dest: "/lib/systemd/system/vault.service"
    owner: root
    group: root
    mode: '0644'
