---
# handlers file for hashicorp_vault
- name: "Enable vault service"
  ansible.builtin.service:
    name: vault
    enabled: true
  listen: "systemctl-enable-vault"

- name: "Start vault service"
  ansible.builtin.service:
    name: vault
    state: restarted
  listen: "systemctl-restart-vault"
  when: hashi_vault_start_service
